### ISSUE TITLE
Can this run in parallel with a Stand Alone DNS ONLY from CPANEL?

### ISSUE THREAD

**Issue by uhlhosting** [jenkstom/python-ddns#1]
Hi,

I am curious if your solution works along side BIND9 in DNSONLY from CPANEL.

**Comment by jenkstom** [comment]
I do not have access to cpanel. 

This works by updating a zone through the BIND9 nsupdate command. If cpanel respects changes made outside of cpanel then I imagine it will work. If cpanel removes and recreates zones when they are updated in cpanel, then I don't imagine it will work.
